# Generated by https://github.com/buildkite/cli/blob/master/.github/tap-release.yml

class Bssl< Formula
  homepage "https://boringssl.googlesource.com/boringssl/"
  desc "BoringSSL is a fork of OpenSSL that is designed to meet Google's needs."
  url "https://boringssl.googlesource.com/boringssl/+archive/1607f54fed72c6589d560254626909a64124f091.tar"
  version "1607f54fed72c6589d560254626909a64124f091"
  sha256 "4e0e20666af36055451cfa46193269d44924e485678161fc039b8cbdc64e486d"

  depends_on "go"
  depends_on "cmake"
  depends_on "ninja" 

  def install
    system "mkdir", "build"
    system "cd", "build"
    system "cmake", "-GNinja", ".."
    system "ninja"
  end

  test do
    assert_match "bk #{version}", shell_output("#{bin}/bk --version 2>&1")
  end
end
